<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0.1</VersionPrefix>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
	<LangVersion>14</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Sandbox.Engine">
      <HintPath>D:\SteamLibrary\steamapps\common\sbox\bin\managed\Sandbox.Engine.dll</HintPath>
      <Private>false</Private>
    </Reference>
        <Reference Include="Sandbox.Mounting">
      <HintPath>D:\SteamLibrary\steamapps\common\sbox\bin\managed\Sandbox.Mounting.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sandbox.System">
      <HintPath>D:\SteamLibrary\steamapps\common\sbox\bin\managed\Sandbox.System.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.34.0" />
</ItemGroup>

<Target Name="ILRepack" AfterTargets="Build">
<ILRepack 
        OutputFile="..\..\..\game\mount\source\source.dll"
        InputAssemblies="$(OutputPath)\$(AssemblyName).dll;$(OutputPath)\MdlCrowbar.dll"
        Internalize="true" />
</Target>


  
  <ItemGroup>
    <PackageReference Include="MdlCrowbar" Version="0.74.1" />
  </ItemGroup>


  
</Project>
